# Site
name: 'Tidbits'
description: 'My own space'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'tid-bits'
email: 'nour.hashem95@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
title : "Tidbits"
include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Noor:
      name:           Noor
      site:           https://github.com/noorhashem
      avatar:         assets/images/avatar1.jpg
      bio:            "An iOS developer who likes to build portable “handy” solutions on your phone, With a knack for AI and Open source software she mixes her interdisciplinary passion, wits and debugging tears into code. A full-time anxious adult who likes to brew some 'hopefully' cool techy/crafty stuff on her secret lab and rant about stuff here or on her various social platforms and bujo. She has multiple interests that won't fit in a short bio, you get the idea. but she'd be ranting about those here anyways."
      email:          nour.hashem95@gmail.com
      twitter:        https://twitter.com/kintsu9i
      github:         https://github.com/noorhashem
      instagram:      https://www.instagram.com/n00rhashem/
      linkedin:       https://www.linkedin.com/in/noormhashem/
     

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Noor
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
